spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stem_guide
    username: stem_guide
    password: stem_guide
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

services:
  ai:
    base-url: http://localhost:8000

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
